### ISSUE TITLE
Add it to awesome-mcp-servers

### ISSUE THREAD

**Issue by punkpeye** [BurtTheCoder/mcp-virustotal#1]
Hey,

this looks like something that should be part of https://github.com/punkpeye/awesome-mcp-servers

Would love your PR to add it

Thank you

**Comment by BurtTheCoder** [comment]
Done also included another for Maigret.  https://github.com/soxoj/maigret

Thanks.

**Comment by punkpeye** [comment]
Amazing. Thanks!
